
package edu.zju.cims201.GOF.service.webservice.qualityservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b02-RC1
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DataServiceService", targetNamespace = "http://service.application.javaplus.org/", wsdlLocation = "http://10.0.52.154:8084/AQB/DataService?WSDL")
public class DataServiceService
    extends Service
{
//
//    private final static URL DATASERVICESERVICE_WSDL_LOCATION;
//
//    static {
//        URL url = null;
//        try {
//            url = new URL("http://10.0.52.154:8084/AQB/DataService?WSDL");
//        } catch (MalformedURLException e) {
//            e.printStackTrace();
//        }
//        DATASERVICESERVICE_WSDL_LOCATION = url;
//    }

    public DataServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

//    public DataServiceService() {
//        super(DATASERVICESERVICE_WSDL_LOCATION, new QName("http://service.application.javaplus.org/", "DataServiceService"));
//    }

    /**
     * 
     * @return
     *     returns DataService
     */
    @WebEndpoint(name = "DataServicePort")
    public DataService getDataServicePort() {
        return (DataService)super.getPort(new QName("http://service.application.javaplus.org/", "DataServicePort"), DataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataService
     */
    @WebEndpoint(name = "DataServicePort")
    public DataService getDataServicePort(WebServiceFeature... features) {
        return null;
        //(DataService)super.getPort(new QName("http://service.application.javaplus.org/", "DataServicePort"), DataService.class, features);
    }

}
