
package edu.zju.cims201.GOF.service.webservice.qualityservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b02-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DataService", targetNamespace = "http://service.application.javaplus.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataService {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "connect", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.Connect")
    @ResponseWrapper(localName = "connectResponse", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.ConnectResponse")
    public byte[] connect(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receive", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.Receive")
    @ResponseWrapper(localName = "receiveResponse", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.ReceiveResponse")
    public byte[] receive(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receiveAQS10Troublereg", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.ReceiveAQS10Troublereg")
    @ResponseWrapper(localName = "receiveAQS10TroubleregResponse", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.ReceiveAQS10TroubleregResponse")
    public String receiveAQS10Troublereg(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receiveAQS10A1", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.ReceiveAQS10A1")
    @ResponseWrapper(localName = "receiveAQS10A1Response", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.ReceiveAQS10A1Response")
    public String receiveAQS10A1(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processEPBA1TMP", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.ProcessEPBA1TMP")
    @ResponseWrapper(localName = "processEPBA1TMPResponse", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.ProcessEPBA1TMPResponse")
    public String processEPBA1TMP(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processEPBTroubleregTMP", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.ProcessEPBTroubleregTMP")
    @ResponseWrapper(localName = "processEPBTroubleregTMPResponse", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.ProcessEPBTroubleregTMPResponse")
    public String processEPBTroubleregTMP(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllA1", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.GetAllA1")
    @ResponseWrapper(localName = "getAllA1Response", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.GetAllA1Response")
    public String getAllA1()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hasAccount", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.HasAccount")
    @ResponseWrapper(localName = "hasAccountResponse", targetNamespace = "http://service.application.javaplus.org/", className = "edu.zju.cims201.GOF.service.webservice.qualityservice.HasAccountResponse")
    public String hasAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

}
